ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_licenseExpiryDate VARCHAR(20);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_licenseExpiryDate DATETIME;
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_supplierId VARCHAR(10);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_status VARCHAR(20);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_actKey VARCHAR(20);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_attachment VARCHAR(100);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_version VARCHAR(20);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_serialNo VARCHAR(30);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_author VARCHAR(100);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_category VARCHAR(30);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_relatedHwId VARCHAR(30);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_description VARCHAR(255);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_purchaseDate VARCHAR(20);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_purchaseDate DATETIME;
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_swId VARCHAR(30);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_po VARCHAR(100);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_notes VARCHAR(255);
ALTER TABLE app_fd_eamms_asset_sw ALTER COLUMN c_license VARCHAR(40);
ALTER TABLE app_fd_eamms_asset_sw DROP COLUMN c_purchasePrice;
ALTER TABLE app_fd_eamms_asset_sw ADD c_purchasePrice NUMERIC(10,2);